export const SHOTS = {
  palm: {
    label: 'Palm',
    contact: 'Topspin',
    targetHeight: 82,
    speed: 835,
    spinScale: 0.9,
    verticalSpin: 1,
    bounceHeight: 1.13,
    bouncePace: 0.94,
    paceScale: 1,
    aimScale: 0.92,
    minWallHeight: 18,
    color: '#d7f36a',
    cue: 'Safe topspin: dips onto the wall, then jumps high off the floor.',
  },
  slice: {
    label: 'Slice',
    contact: 'Backspin',
    targetHeight: 62,
    speed: 805,
    spinScale: 1.45,
    verticalSpin: -1,
    bounceHeight: 0.68,
    bouncePace: 1.08,
    paceScale: 0.96,
    aimScale: 1.02,
    minWallHeight: 14,
    color: '#7de4dc',
    cue: 'Undercut backspin floats, then skids low and carries through the court.',
  },
  fist: {
    label: 'Fist',
    contact: 'Knuckle',
    targetHeight: 70,
    speed: 930,
    spinScale: 0.15,
    verticalSpin: 0,
    bounceHeight: 0.9,
    bouncePace: 1.03,
    paceScale: 1.08,
    aimScale: 1.16,
    minWallHeight: 16,
    color: '#ffb84d',
    cue: 'Heavy knuckle pace with almost no spin—and less margin near the lines.',
  },
  backhand: {
    label: 'Backhand',
    contact: 'Reverse',
    targetHeight: 72,
    speed: 825,
    spinScale: 1.2,
    verticalSpin: -0.2,
    bounceHeight: 0.84,
    bouncePace: 1.02,
    paceScale: 0.98,
    aimScale: 1.18,
    minWallHeight: 14,
    color: '#e5a9ff',
    cue: 'Quick reverse-hand contact opens sharp cross-court angles.',
  },
  flat: {
    label: 'Flat',
    contact: 'Serve',
    targetHeight: 78,
    speed: 840,
    spinScale: 1,
    verticalSpin: 0,
    bounceHeight: 1,
    bouncePace: 1,
    paceScale: 1,
    aimScale: 1,
    minWallHeight: 18,
    color: '#ffd66b',
    cue: 'Balanced pace and the safest line to the wall.',
  },
  lob: {
    label: 'Lob',
    contact: 'Lift',
    targetHeight: 132,
    speed: 730,
    spinScale: 0.75,
    verticalSpin: 0.5,
    bounceHeight: 1.18,
    bouncePace: 0.88,
    paceScale: 0.88,
    aimScale: 0.78,
    minWallHeight: 42,
    color: '#8fc9ff',
    cue: 'Higher arc that buys you recovery time.',
  },
  kill: {
    label: 'Kill',
    contact: 'Drive',
    targetHeight: 34,
    speed: 940,
    spinScale: 0.55,
    verticalSpin: -0.35,
    bounceHeight: 0.58,
    bouncePace: 1.08,
    paceScale: 1.12,
    aimScale: 1.24,
    minWallHeight: 10,
    color: '#ff7048',
    cue: 'Low missile. Great if you catch it early, brutal if you miss.',
  },
  roller: {
    label: 'Roller',
    contact: 'Crack',
    targetHeight: 12,
    speed: 890,
    spinScale: 0.35,
    verticalSpin: -1.2,
    bounceHeight: 0.25,
    bouncePace: 1.12,
    paceScale: 1.02,
    aimScale: 1.42,
    minWallHeight: 6,
    color: '#ff4d83',
    cue: 'Crack-level finish. Only clean, low contact keeps this out of the floor.',
  },
};

export const SHOT_TIMING = {
  flat: { loadTime: 0.66, sweetStart: 0.5, sweetEnd: 0.84 },
  palm: { loadTime: 0.72, sweetStart: 0.55, sweetEnd: 0.82 },
  slice: { loadTime: 0.68, sweetStart: 0.48, sweetEnd: 0.78 },
  fist: { loadTime: 0.76, sweetStart: 0.62, sweetEnd: 0.84 },
  backhand: { loadTime: 0.62, sweetStart: 0.43, sweetEnd: 0.74 },
  kill: { loadTime: 0.7, sweetStart: 0.56, sweetEnd: 0.78 },
  roller: { loadTime: 0.8, sweetStart: 0.64, sweetEnd: 0.78 },
  lob: { loadTime: 0.7, sweetStart: 0.42, sweetEnd: 0.86 },
};

export const DIFFICULTIES = {
  easy: {
    label: 'Easy',
    opponent: 'Rookie Rae',
    style: 'The Floater',
    tactic: 'High palms, patient lobs, and generous center-court targets.',
    speedScale: 0.88,
    anticipationSeconds: 0.03,
    predictionBlend: 0.22,
    targetOffset: 42,
    reachBonus: -6,
    shotWeights: { palm: 0.42, slice: 0.22, fist: 0.12, backhand: 0.1, lob: 0.12, kill: 0.02, roller: 0 },
    returnSpeedScale: 0.92,
    reactionDelay: 0.13,
    contactHeight: 32,
    recoveryDepth: 76,
    recoveryCenter: 0.84,
    movementResponse: 10,
    openCourtAim: 0.18,
    adaptation: 0.12,
    description: 'Slower feet, floatier replies, friendlier pressure.',
  },
  medium: {
    label: 'Medium',
    opponent: 'Wall Ghost',
    style: 'The Counterpuncher',
    tactic: 'Reads your position, redirects pace, and shades the open wall.',
    speedScale: 1,
    anticipationSeconds: 0.07,
    predictionBlend: 0.54,
    targetOffset: 28,
    reachBonus: 0,
    shotWeights: { palm: 0.3, slice: 0.2, fist: 0.18, backhand: 0.12, lob: 0.1, kill: 0.08, roller: 0.02 },
    returnSpeedScale: 1,
    reactionDelay: 0.075,
    contactHeight: 42,
    recoveryDepth: 48,
    recoveryCenter: 0.62,
    movementResponse: 13,
    openCourtAim: 0.62,
    adaptation: 0.5,
    description: 'Balanced court coverage and honest rally pace.',
  },
  hard: {
    label: 'Hard',
    opponent: 'King Shade',
    style: 'The Crack Hunter',
    tactic: 'Cuts the court early, attacks low balls, and hunts the open crack.',
    speedScale: 1.12,
    anticipationSeconds: 0.11,
    predictionBlend: 0.82,
    targetOffset: 16,
    reachBonus: 8,
    shotWeights: { palm: 0.2, slice: 0.18, fist: 0.2, backhand: 0.14, lob: 0.06, kill: 0.16, roller: 0.06 },
    returnSpeedScale: 1.08,
    reactionDelay: 0.025,
    contactHeight: 54,
    recoveryDepth: 24,
    recoveryCenter: 0.42,
    movementResponse: 16,
    openCourtAim: 0.92,
    adaptation: 0.9,
    description: 'Sharper reads, tighter spacing, and meaner putaways.',
  },
};

export const TRAINING_DRILLS = {
  corners: {
    name: 'Tag the Boroughs',
    goal: 8,
    maxAttempts: 12,
    prompt: 'Paint the glowing wall target',
  },
  spin: {
    name: 'Spin Doctor',
    goal: 8,
    maxAttempts: 10,
    sequence: ['palm', 'slice', 'fist', 'backhand', 'palm', 'slice', 'fist', 'backhand'],
    prompt: 'Match the called hand contact',
  },
  kill: {
    name: 'Crack Hunter',
    goal: 6,
    maxAttempts: 10,
    prompt: 'Kill or roll it below the tape',
  },
  rally: {
    name: 'Stay Alive',
    goal: 10,
    maxMisses: 3,
    prompt: 'Ten legal wall returns without a miss',
  },
};

export const AVATAR_OPTIONS = {
  skin: {
    label: 'Skin tone',
    options: [
      { id: 'porcelain', label: 'Porcelain', color: '#f6d2bd' },
      { id: 'peach', label: 'Peach', color: '#eeb995' },
      { id: 'golden', label: 'Golden', color: '#d99a62' },
      { id: 'olive', label: 'Olive', color: '#b97b50' },
      { id: 'bronze', label: 'Bronze', color: '#96603f' },
      { id: 'umber', label: 'Umber', color: '#70442f' },
      { id: 'deep', label: 'Deep', color: '#4c2d25' },
      { id: 'ebony', label: 'Ebony', color: '#2c1b1a' },
    ],
  },
  build: {
    label: 'Body type',
    options: [
      { id: 'compact', label: 'Compact', scale: 0.92, width: 1.04 },
      { id: 'lean', label: 'Lean', scale: 1.04, width: 0.88 },
      { id: 'athletic', label: 'Athletic', scale: 1, width: 1 },
      { id: 'power', label: 'Power', scale: 1.05, width: 1.16 },
    ],
  },
  face: {
    label: 'Face',
    options: [
      { id: 'focused', label: 'Focused' },
      { id: 'soft', label: 'Soft' },
      { id: 'grin', label: 'Grin' },
      { id: 'tough', label: 'Tough' },
      { id: 'wide', label: 'Wide-eyed' },
    ],
  },
  facialHair: {
    label: 'Facial hair',
    options: [
      { id: 'none', label: 'Clean shave' },
      { id: 'stubble', label: 'Stubble' },
      { id: 'mustache', label: 'Mustache' },
      { id: 'goatee', label: 'Goatee' },
      { id: 'beard', label: 'Full beard' },
    ],
  },
  hair: {
    label: 'Hair',
    options: [
      { id: 'buzz', label: 'Buzz', color: '#171316' },
      { id: 'fade', label: 'Fade', color: '#2a1a14' },
      { id: 'curls', label: 'Curls', color: '#251713' },
      { id: 'afro', label: 'Afro', color: '#181215' },
      { id: 'braids', label: 'Braids', color: '#201416' },
      { id: 'locs', label: 'Locs', color: '#211512' },
      { id: 'mohawk', label: 'Mohawk', color: '#ff4d83' },
      { id: 'ponytail', label: 'Ponytail', color: '#3b2318' },
    ],
  },
  top: {
    label: 'Top',
    options: [
      { id: 'blackTank', label: 'Black tank', color: '#151b22', accent: '#d7f36a' },
      { id: 'cityTee', label: 'City tee', color: '#f1eee5', accent: '#ff4d83' },
      { id: 'parkJersey', label: 'Park jersey', color: '#ff9f38', accent: '#071018' },
      { id: 'graffitiTee', label: 'Graffiti tee', color: '#7de4dc', accent: '#842c5b' },
      { id: 'hoodie', label: 'Hoodie', color: '#713c8c', accent: '#e5a9ff' },
      { id: 'cropSport', label: 'Sport crop', color: '#ff4d83', accent: '#ffd66b' },
      { id: 'denimVest', label: 'Denim vest', color: '#31577a', accent: '#f1eee5' },
      { id: 'sunTank', label: 'Sun tank', color: '#d7f36a', accent: '#071018' },
    ],
  },
  palette: {
    label: 'Outfit colorway',
    options: [
      { id: 'original', label: 'Original', color: '#ff9f38' },
      { id: 'subway', label: 'Subway steel', color: '#cfe3eb', top: '#263b4a', accent: '#ffb84d', bottom: '#101820' },
      { id: 'electric', label: 'Electric park', color: '#d7f36a', top: '#713c8c', accent: '#d7f36a', bottom: '#18242c' },
      { id: 'sunset', label: 'City sunset', color: '#ff7048', top: '#c45057', accent: '#ffd66b', bottom: '#3c254f' },
      { id: 'aqua', label: 'Hydrant aqua', color: '#7de4dc', top: '#16646c', accent: '#f1eee5', bottom: '#263b4a' },
      { id: 'blackout', label: 'Blacktop', color: '#151b22', top: '#111820', accent: '#ff4d83', bottom: '#080d12' },
    ],
  },
  emblem: {
    label: 'Chest emblem',
    options: [
      { id: 'none', label: 'None' },
      { id: 'wall', label: 'W' },
      { id: 'four', label: 'West 4' },
      { id: 'star', label: 'Star' },
      { id: 'crown', label: 'Crown' },
      { id: 'bolt', label: 'Bolt' },
      { id: 'blocks', label: 'Borough blocks' },
    ],
  },
  bottom: {
    label: 'Bottoms',
    options: [
      { id: 'courtShorts', label: 'Court shorts', color: '#101820' },
      { id: 'trackPants', label: 'Track pants', color: '#263b4a' },
      { id: 'jeans', label: 'Jeans', color: '#31577a' },
      { id: 'cargos', label: 'Cargos', color: '#59614a' },
      { id: 'leggings', label: 'Leggings', color: '#3c254f' },
      { id: 'boardShorts', label: 'Board shorts', color: '#c45057' },
    ],
  },
  headwear: {
    label: 'Headwear',
    options: [
      { id: 'none', label: 'None', color: 'transparent' },
      { id: 'fitted', label: 'Fitted', color: '#ff9f38' },
      { id: 'bucket', label: 'Bucket', color: '#d7f36a' },
      { id: 'bandana', label: 'Bandana', color: '#ff4d83' },
      { id: 'beanie', label: 'Beanie', color: '#7de4dc' },
    ],
  },
  shoes: {
    label: 'Footwear',
    options: [
      { id: 'highTops', label: 'High tops', color: '#f1eee5' },
      { id: 'runners', label: 'Runners', color: '#d7f36a' },
      { id: 'skateLows', label: 'Skate lows', color: '#ff4d83' },
      { id: 'boots', label: 'Boots', color: '#5b392b' },
      { id: 'slides', label: 'Slides', color: '#7de4dc' },
      { id: 'retro', label: 'Retro court', color: '#ff9f38' },
    ],
  },
  accessory: {
    label: 'Jewelry & tape',
    options: [
      { id: 'none', label: 'None' },
      { id: 'chain', label: 'Gold chain', color: '#ffd66b' },
      { id: 'hoops', label: 'Hoops', color: '#ffd66b' },
      { id: 'wristTape', label: 'Wrist tape', color: '#f1eee5' },
      { id: 'silverChain', label: 'Silver chain', color: '#cfe3eb' },
    ],
  },
  eyewear: {
    label: 'Eyewear',
    options: [
      { id: 'none', label: 'None' },
      { id: 'shades', label: 'Black shades', color: '#071018' },
      { id: 'sport', label: 'Sport shield', color: '#ff4d83' },
      { id: 'clear', label: 'Clear frames', color: '#cfe3eb' },
    ],
  },
  bodyart: {
    label: 'Body art',
    options: [
      { id: 'none', label: 'None' },
      { id: 'armInk', label: 'Arm ink', color: '#26333b' },
      { id: 'sleeve', label: 'Full sleeve', color: '#17242c' },
    ],
  },
};

export const DEFAULT_AVATAR = {
  name: 'You',
  skin: 'golden',
  build: 'athletic',
  face: 'focused',
  facialHair: 'none',
  hair: 'fade',
  top: 'parkJersey',
  palette: 'original',
  emblem: 'wall',
  bottom: 'courtShorts',
  headwear: 'none',
  shoes: 'highTops',
  accessory: 'wristTape',
  eyewear: 'none',
  bodyart: 'none',
};

export const AVATAR_PRESETS = {
  parkAce: { skin: 'bronze', build: 'athletic', face: 'grin', facialHair: 'stubble', hair: 'fade', top: 'parkJersey', palette: 'sunset', emblem: 'four', bottom: 'courtShorts', headwear: 'fitted', shoes: 'retro', accessory: 'wristTape', eyewear: 'sport', bodyart: 'none' },
  uptownBreaker: { skin: 'deep', build: 'lean', face: 'focused', facialHair: 'none', hair: 'braids', top: 'graffitiTee', palette: 'electric', emblem: 'bolt', bottom: 'trackPants', headwear: 'beanie', shoes: 'highTops', accessory: 'chain', eyewear: 'none', bodyart: 'armInk' },
  lesSkater: { skin: 'peach', build: 'compact', face: 'soft', facialHair: 'none', hair: 'curls', top: 'cityTee', palette: 'aqua', emblem: 'star', bottom: 'cargos', headwear: 'fitted', shoes: 'skateLows', accessory: 'none', eyewear: 'shades', bodyart: 'armInk' },
  boardwalkHippy: { skin: 'olive', build: 'lean', face: 'grin', facialHair: 'mustache', hair: 'ponytail', top: 'sunTank', palette: 'sunset', emblem: 'blocks', bottom: 'boardShorts', headwear: 'bandana', shoes: 'slides', accessory: 'hoops', eyewear: 'clear', bodyart: 'none' },
  downtownBruiser: { skin: 'umber', build: 'power', face: 'tough', facialHair: 'beard', hair: 'buzz', top: 'blackTank', palette: 'blackout', emblem: 'crown', bottom: 'jeans', headwear: 'none', shoes: 'boots', accessory: 'chain', eyewear: 'none', bodyart: 'sleeve' },
  cageVeteran: { skin: 'ebony', build: 'athletic', face: 'focused', facialHair: 'goatee', hair: 'locs', top: 'denimVest', palette: 'subway', emblem: 'wall', bottom: 'courtShorts', headwear: 'bucket', shoes: 'runners', accessory: 'silverChain', eyewear: 'shades', bodyart: 'armInk' },
};

export const RIVAL_AVATARS = {
  easy: { skin: 'peach', build: 'compact', face: 'wide', facialHair: 'none', hair: 'curls', top: 'cityTee', palette: 'aqua', emblem: 'star', bottom: 'courtShorts', headwear: 'fitted', shoes: 'skateLows', accessory: 'wristTape', eyewear: 'none', bodyart: 'none' },
  medium: { skin: 'deep', build: 'lean', face: 'focused', facialHair: 'goatee', hair: 'braids', top: 'graffitiTee', palette: 'electric', emblem: 'wall', bottom: 'trackPants', headwear: 'beanie', shoes: 'highTops', accessory: 'silverChain', eyewear: 'clear', bodyart: 'armInk' },
  hard: { skin: 'umber', build: 'power', face: 'tough', facialHair: 'beard', hair: 'locs', top: 'blackTank', palette: 'blackout', emblem: 'crown', bottom: 'cargos', headwear: 'none', shoes: 'boots', accessory: 'chain', eyewear: 'shades', bodyart: 'sleeve' },
};
